name: Docker React

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t tusharshrivastava/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true tusharshrivastava/docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
